services:
  inc-bot:
    image: inc-bot-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Inc-Bot
    volumes:
      - type: bind
        source: ${STATE_DIR}/state.json
        target: /App/state.json
        bind:
          create_host_path: true
